/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'acs49' at '06/04/17 12:36' with Gradle 2.14.1
 *
 * @author acs49, @date 06/04/17 12:36
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
